package com.yowyob.loyalty.shared.exception;

public enum ErrorCode {
    TENANT_NOT_FOUND(404),
    TENANT_SUSPENDED(403),
    TENANT_NOT_READY(403),
    TENANT_CONTEXT_MISSING(500),
    JWT_INVALID(401),
    JWT_EXPIRED(401),
    JWT_MISSING(401),
    MISSING_TENANT_CLAIM(401),
    CROSS_TENANT_ACCESS_DENIED(403),
    FORBIDDEN(403),
    IDEMPOTENCY_CONFLICT(409),
    INTERNAL_ERROR(500),
    VALIDATION_ERROR(400),
    RESOURCE_NOT_FOUND(404),
    BONIFICATION_UNAVAILABLE(502),
    KERNEL_CORE_UNAVAILABLE(502),
    INVALID_CREDENTIALS(401),
    ORGANIZATION_SELECTION_REQUIRED(400),
    ORGANIZATION_NOT_ACCESSIBLE(403),

    // Module Rewards
    REWARD_NOT_FOUND(404),
    REWARD_NOT_AVAILABLE(422),
    REWARD_STOCK_EXHAUSTED(409),
    REWARD_NOT_REDEEMABLE(422),
    GRANT_NOT_FOUND(404),
    GRANT_ALREADY_USED(409),
    GRANT_EXPIRED(410),
    GRANT_CANCELLED(422),
    GRANT_NOT_OWNED_BY_MEMBER(403),
    INSUFFICIENT_POINTS_FOR_REDEMPTION(422),
    REWARD_CATALOG_EMPTY(404),

    // Module Referral
    REFERRAL_PROGRAM_NOT_FOUND(404),
    REFERRAL_LINK_NOT_FOUND(404),
    REFERRAL_ALREADY_ENROLLED(409),
    REFERRAL_ALREADY_CONVERTED(409),
    SELF_REFERRAL_NOT_ALLOWED(422),
    REFERRAL_LINK_EXPIRED(410),
    REFERRAL_CONVERSION_AMOUNT_TOO_LOW(422),
    REFERRAL_PROGRAM_INACTIVE(422),
    MAX_REFERRALS_EXCEEDED(422),

    // Module Campagnes
    CAMPAIGN_NOT_FOUND(404),
    CAMPAIGN_ALREADY_TERMINAL(422),
    CAMPAIGN_INVALID_TRANSITION(422),

    // Module Codes Promo
    PROMO_CAMPAIGN_NOT_FOUND(404),
    PROMO_NOT_ACTIVE(422),
    PROMO_NOT_STARTED(422),
    PROMO_EXPIRED(410),
    PROMO_EXHAUSTED(409),
    PROMO_ALREADY_USED(409),
    PROMO_MIN_ORDER_AMOUNT_NOT_MET(422),

    // Module Abonnements SaaS
    PLAN_NOT_FOUND(404),
    SUBSCRIPTION_NOT_FOUND(404),
    ALREADY_SUBSCRIBED(409),
    SUBSCRIPTION_ALREADY_TERMINAL(422);

    private final int httpStatus;

    ErrorCode(int httpStatus) {
        this.httpStatus = httpStatus;
    }

    public int getHttpStatus() {
        return httpStatus;
    }
}
